# Use a imagem do OpenJDK 17
FROM openjdk:17-jdk-slim

# Defina o diretório de trabalho no contêiner
WORKDIR /app

# Copie o arquivo JAR gerado pela aplicação para o contêiner
COPY target/carteira-digital.war /app/carteira-digital.war

# Comando para executar a aplicação
ENTRYPOINT ["java", "-jar", "/app/carteira-digital.war"]